#!/bin/bash

if [ $# -ne 2 ] && [ $# -ne 1 ] || [ "$1" = '--help' ];
then
    echo -e "PFED Copyright (C) 2022 linux-coding649\n
    This program comes with ABSOLUTELY NO WARRANTY; for details type `pfed --license'.\n
    This is free software, and you are welcome to redistribute it\n
    under certain conditions; type `pfed --license' for details.\nUsage: pfed filename"
    exit 0
elif [ $# -ne 2 ] && [ $# -ne 1 ] || [ "$1" = '--license' ];
then
    echo -e "This program complies with the GNU General Public License Version 3\n"
fi

if [ -e "$1" ];
then
    touch "$1".tmp
    cat "$1" >> "$1".tmp
    if [ -x /usr/bin/nano ];
    then
        echo "Using the nano editor..."
        sleep 1
        nano "$1".tmp
    elif [ -x /usr/bin/emacs ];
    then
        echo "Using the emacs editor..."
        sleep 1
        emacs "$1".tmp
    elif [ -x /usr/bin/vim ];
    then
        echo "Using the vim editor..."
        sleep 1
        vim "$1".tmp
    else
        echo "No supported file editor."
        rm "$1".tmp
        exit 1
    fi
    mv -f "$1".tmp "$1"
    chmod 400 "$1"
else
    if [ -x /usr/bin/nano ];
    then
        echo "Using the nano editor..."
        sleep 1
        nano "$1".tmp
    elif [ -x /usr/bin/emacs ];
    then
        echo "Using the emacs editor..."
        sleep 1
        emacs "$1".tmp
    elif [ -x /usr/bin/vim ];
    then
        echo "Using the vim editor..."
        sleep 1
        vim "$1".tmp
    else
        echo "No supported file editor."
        rm "$1".tmp
        exit 1
    fi
    mv -f "$1".tmp "$1"
    chmod 400 "$1"
fi

echo 'Done!'
exit 0
